import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { ClerkProvider } from "@clerk/nextjs";
import { GlobalContextProvider } from "@/components/utils/store";
import NavbarComponent from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <ClerkProvider>
            <Providers>
              <GlobalContextProvider>
                <NavbarComponent />
                {children}{" "}
              </GlobalContextProvider>
            </Providers>
          </ClerkProvider>
        </body>
      </html>
    </>
  );
}
